@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package Logic <<rectangle>> {
    class LogicManager as "<u>:LogicManager</u>"
    class State1 as "<u>ab0:AddressBook</u>"
}

LogicManager -[hidden]right-> State1
class Pointer as "Current State" #FFFFFF

Pointer -up-> State1
@end
