@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "delete 1"

package Logic <<rectangle>> {
    class LogicManager as "<u>:LogicManager</u>"
    class UndoableCommand1 as "<u>:DeleteCommand</u>"
    class State1 as "<u>ab0:AddressBook</u>"
    class State2 as "<u>ab1:AddressBook</u>"
}

LogicManager -[hidden]right-> State1
LogicManager -right-> UndoableCommand1
UndoableCommand1 -right-> State1
State1 -[hidden]up-> State2
class Pointer1 as "Current State" #FFFFFF
class Pointer2 as "Most Recent" #FFFFFF
Pointer1 -down-> State2
Pointer2 -up-> UndoableCommand1
@end
